export const ecommerceCartItemFixtures = {
  aMonthlySubscriptionItem: {
    discount: 0,
    id: "aSubscriptionId",
    productId: "aSubscriptionId",
    slug: "aSubscriptionId",
    name: "Subscription",
    options: [
      {
        name: "Plan",
        value: "Monthly",
      },
    ],
    price: 0,
    quantity: 1,
    bundleItems: [],
    isSubscription: true,
    hasSubscriptionPackage: false,
  },
  aYearlySubscriptionItem: {
    discount: 0,
    id: "61897fd97c62f941f81c5033",
    productId: "abcdef123456",
    slug: "abcdef123456",
    name: "Subscription",
    options: [
      {
        name: "Plan",
        value: "Yearly",
      },
    ],
    price: 0,
    quantity: 1,
    bundleItems: [],
    isSubscription: true,
    hasSubscriptionPackage: false,
  },
  aChargeableYearlySubscriptionItem: {
    discount: 0,
    id: "61897fd97c62f941f81c5033",
    productId: "abcdef123456",
    slug: "abcdef123456",
    name: "Subscription",
    options: [
      {
        name: "Subscription",
        value: "Yearly",
      },
    ],
    price: 0,
    quantity: 1,
    bundleItems: [],
    isSubscription: true,
    hasSubscriptionPackage: false,
  },
  aMaxRowerItem: {
    discount: 0,
    id: "aMaxRowerId",
    productId: "aMaxRowerId",
    slug: "aMaxRowerId",
    name: "Max Rower",
    options: [],
    price: 123,
    quantity: 1,
    bundleItems: [],
    isSubscription: false,
    hasSubscriptionPackage: true,
  },
  aClassicRowerItem: {
    discount: 0,
    id: "aClassicRowerId",
    productId: "abcdef123456",
    slug: "abcdef123456",
    name: "Classic Rower",
    options: [],
    price: 100,
    quantity: 1,
    bundleItems: [],
    isSubscription: false,
    hasSubscriptionPackage: true,
  },
  aComModuleItem: {
    discount: 0,
    id: "aComModuleId",
    productId: "abcdef123456",
    slug: "abcdef123456",
    name: "CityRow ComModule",
    options: [],
    price: 35,
    quantity: 1,
    bundleItems: [],
    isSubscription: false,
    hasSubscriptionPackage: true,
  },
  aTShirtItem: {
    discount: 0,
    id: "a TShirt",
    productId: "abcdef123456",
    slug: "abcdef123456",
    name: "T Shirt",
    options: [],
    price: 5,
    quantity: 1,
    bundleItems: [],
    isSubscription: false,
    hasSubscriptionPackage: false,
  },
};
