import { klarnaSessionFixtures } from "../../payment/testing/KlarnaSessionFixtures";
import { cardFixtures } from "./CardFixtures";

export const orderFixtures = {
  anOrderRequestWithCardAndAmount4000: {
    account: {
      email: "test@test.com",
      contactMe: true,
      password: "thepassword",
    },
    address: "Olive Drive 560",
    amount: 4000,
    authorizationToken: undefined,
    card: cardFixtures.aCard,
    city: "Ellinwood",
    country: "US",
    currency: "usd",
    firstName: "Test",
    klarnaSession: undefined,
    lastName: "User",
    paymentIntent: "aPaymentIntent",
    paymentMethod: "card",
    postalCode: "67526",
    phone: "620-564-3737",
    state: "KS",
  },
  anOrderRequestWithCardAndAmount0: {
    account: {
      email: "test@test.com",
      contactMe: true,
      password: "thepassword",
    },
    address: "Olive Drive 560",
    amount: 0,
    authorizationToken: undefined,
    card: cardFixtures.aCard,
    city: "Ellinwood",
    country: "US",
    currency: "usd",
    firstName: "Test",
    klarnaSession: undefined,
    lastName: "User",
    paymentIntent: undefined,
    paymentMethod: "card",
    postalCode: "67526",
    phone: "620-564-3737",
    state: "KS",
  },
  anOrderRequestLoggedInWithCardAndAmount4000: {
    address: "Olive Drive 560",
    amount: 4000,
    authorizationToken: undefined,
    card: cardFixtures.aCard,
    city: "Ellinwood",
    country: "US",
    currency: "usd",
    firstName: "Test",
    klarnaSession: undefined,
    lastName: "User",
    paymentIntent: "aPaymentIntent",
    paymentMethod: "card",
    phone: "620-564-3737",
    state: "KS",
    postalCode: "67526",
  },
  anOrderRequestWithKlarnaWithAmount4000: {
    account: {
      email: "test@test.com",
      contactMe: true,
      password: "thepassword",
    },
    address: "Olive Drive 560",
    amount: 4000,
    authorizationToken: "anAuthorizationToken",
    card: undefined,
    city: "Ellinwood",
    country: "US",
    currency: "usd",
    firstName: "Test",
    klarnaSession: klarnaSessionFixtures.aKlarnaSession,
    lastName: "User",
    paymentIntent: undefined,
    paymentMethod: "klarna",
    phone: "620-564-3737",
    state: "KS",
    postalCode: "67526",
  },
  anOrder: {
    account: {
      firstName: "user",
    },
    accountId: "anAccountId",
    cardToken: "aToken",
    coupon: "aCoupon",
    currency: "USD",
    discounts: 50,
    id: "someId",
    items: [
      {
        discount: 50,
        discountEach: 50,
        hasSalePrice: false,
        name: "someName",
        options: [{ id: "someId", value: "someValue" }],
        originalPrice: 1850,
        price: 1850,
        product: {
          id: "aProductId",
          isSubscription: false,
          name: "aProductName",
          options: [{ attributeId: "color", values: [{ name: "white", paymentPlanId: "" }] }],
          sku: "someSku",
        },
        quantity: 1,
      },
    ],
    number: "123456",
    paymentMethod: "card" as "card" | "klarna",
    shipmentTotal: 100,
    shipping: {
      city: "",
      country: "",
      deliveryType: "Parcel Delivery",
      name: "",
      state: "",
      street: "",
      zip: "",
    },
    subTotal: 1850,
    taxes: 200,
    total: 2150,
  },
  anOrderWithKlarna: {
    accountId: "anAccountId",
    cardToken: "aToken",
    items: [
      {
        quantity: 1,
        options: [],
        product: {
          options: [{ attributeId: "color", values: [{ name: "white", paymentPlanId: "" }] }],
          isSubscription: false,
          sku: "someSku",
        },
      },
    ],
    paymentMethod: "klarna",
  },
  anOrderWithSubscription: {
    accountId: "anAccountId",
    currency: "USD",
    coupon: "aCoupon",
    shipmentTotal: 0,
    id: "someId",
    account: {
      firstName: "user",
    },
    shipping: {
      city: "",
      country: "",
      deliveryType: "",
      name: "",
      state: "",
      street: "",
      zip: "",
    },
    discounts: 0,
    subTotal: 0,
    delivery: 0,
    total: 0,
    taxes: 0,
    number: "123456",
    cardToken: "aToken",
    items: [
      {
        discount: 0,
        discountEach: 0,
        hasSalePrice: false,
        name: "Subscription",
        quantity: 1,
        price: 0,
        originalPrice: 0,
        options: [{ id: "Plan", value: "Monthly" }],
        product: {
          id: "",
          name: "",
          options: [{ attributeId: "subscription", values: [{ name: "Monthly", paymentPlanId: "aPaymentPlanId" }] }],
          isSubscription: true,
          sku: "someSku",
        },
      },
    ],
    paymentMethod: "card" as "card" | "klarna",
  },
  anOrderWithSubscriptionWithKlarna: {
    accountId: "anAccountId",
    cardToken: "aToken",
    items: [
      {
        quantity: 1,
        options: [{ id: "Subscription", value: "Yearly" }],
        product: {
          options: [{ attributeId: "subscription", values: [{ name: "Yearly", paymentPlanId: "aPaymentPlanId" }] }],
          isSubscription: true,
          sku: "someSku",
        },
      },
    ],
    paymentMethod: "klarna",
    shipping: {
      city: "",
      country: "",
      deliveryType: "",
      name: "",
      state: "",
      street: "",
      zip: "",
    },
  },
};
