export const productFixtures = {
  aProduct: {
    bundleItems: [],
    categories: [],
    crossSellProducts: [],
    canBuyWithoutStock: false,
    description: "a description",
    id: "anId",
    images: [],
    isSubscription: false,
    name: "a name",
    options: [],
    price: 123,
    priceWithoutSale: 123,
    priceClarification: "a price clarification",
    relatedProducts: [],
    hasSubscriptionPackage: false,
    sku: "a sku",
    slug: "a slug",
    stock: 321,
    stockTracking: false,
    subscriptions: [],
    subtitle: "a subtitle",
    upSellProducts: [],
    variants: [],
  },
  aProductWithVariants: {
    bundleItems: [],
    categories: [],
    crossSellProducts: [],
    canBuyWithoutStock: false,
    description: "a description",
    id: "anId",
    images: [],
    isBundle: false,
    isSubscription: false,
    name: "a name",
    options: [
      {
        attributeId: "size",
        name: "Size",
        values: [
          {
            id: "option1",
            name: "XS",
            description: "",
            price: 0,
          },
          {
            id: "option2",
            name: "XL",
            description: "",
            price: 0,
          },
        ],
      },
    ],
    price: 123,
    priceWithoutSale: 123,
    priceClarification: "a price clarification",
    relatedProducts: [],
    hasSubscriptionPackage: false,
    sku: "a sku",
    slug: "a slug",
    stock: 321,
    stockTracking: false,
    subscriptions: [],
    subtitle: "a subtitle",
    upSellProducts: [],
    variants: [
      {
        id: "variant1",
        name: "30lb",
        optionsIds: ["option1"],
        images: [],
        price: 10,
        stock: 3,
        description: "test",
      },
      {
        id: "variant2",
        name: "25lb",
        optionsIds: ["option2"],
        images: [],
        price: 20,
        stock: 1,
        description: "test",
      },
    ],
  },
  aDumbBell: {
    acceptsMultipleVariants: true,
    bundleItems: [],
    categories: ["accessories"],
    canBuyWithoutStock: false,
    crossSellProducts: [],
    description: "a description",
    id: "60e463b039fe8075bb2a9b8c",
    images: ["https://cdn.schema.io/cityrow-staging/612557c10b7d1e73afa5b13a/c526f0f8c69cf99fbc62fcdccf0f0410"],
    isSubscription: false,
    options: [
      {
        attributeId: "weight",
        name: "Weight",
        values: [
          {
            id: "60f72d94bacf01fb2a5cfe20",
            name: "25lb",
            description: "test",
            price: 10,
          },
          {
            id: "60f72d94bacf01fb2a5cfe21",
            name: "30lb",
            description: "test",
            price: 20,
          },
        ],
      },
    ],
    name: "Dumbbells",
    stockTracking: false,
    subtitle: "a subtitle",
    price: 60,
    priceClarification: "excludes tax and shipping",
    relatedProducts: [],
    hasSubscriptionPackage: false,
    sku: "cr-weight",
    slug: "cr-weight",
    specs: "<em>Size of dumbbell is based on weight.</em><br>",
    stock: 0,
    subscriptions: [],
    upSellProducts: [],
    variants: [
      {
        id: "6150342b6c0ba95d87564db6",
        name: "30lb",
        optionsIds: ["60f72d94bacf01fb2a5cfe21"],
        images: [],
        price: 80,
        stock: 1,
        description: "test",
        quantity: 1,
      },
      {
        id: "6150342b6c0ba95d87564db5",
        name: "25lb",
        optionsIds: ["60f72d94bacf01fb2a5cfe20"],
        images: [],
        price: 70,
        stock: 1,
        description: "test",
        quantity: 1,
      },
    ],
  },
  dumbBellVariantsVM: [
    {
      description: "a description",
      id: "6150342b6c0ba95d87564db6",
      images: [],
      name: "30lb",
      optionsIds: ["60f72d94bacf01fb2a5cfe21"],
      price: "$80",
      stock: 10,
    },
    {
      description: "a description",
      id: "6150342b6c0ba95d87564db6",
      images: [],
      name: "25lb",
      optionsIds: ["60f72d94bacf01fb2a5cfe20"],
      price: "$70",
      stock: 7,
    },
  ],
  aSubscriptionProduct: {
    bundleItems: [],
    canBuyWithoutStock: false,
    categories: ["Subscription"],
    crossSellProducts: [],
    description: "a description",
    id: "someId",
    images: ["someImage"],
    isSubscription: true,
    name: "a name",
    options: [],
    price: 0,
    priceClarification: "a price clarification",
    relatedProducts: [],
    hasSubscriptionPackage: false,
    sku: "someSku",
    slug: "a slug",
    stock: 321,
    stockTracking: false,
    subscriptions: [],
    subtitle: "a subtitle",
    upSellProducts: [],
    variants: [],
  },
  aMaxRower: {
    bundleItems: [],
    categories: ["Rower"],
    canBuyWithoutStock: false,
    crossSellProducts: [],
    description: "a description",
    id: "someId",
    images: ["someImages"],
    isSubscription: false,
    name: "max-rower",
    options: [],
    price: 123,
    priceClarification: "a price clarification",
    relatedProducts: [],
    hasSubscriptionPackage: true,
    sku: "someSku",
    slug: "a slug",
    stock: 321,
    stockTracking: false,
    subscriptions: [],
    subtitle: "a subtitle",
    upSellProducts: [],
    variants: [],
  },
  aClassicRower: {
    bundleItems: [],
    categories: ["Rower"],
    canBuyWithoutStock: false,
    crossSellProducts: [],
    description: "a description",
    id: "someId",
    images: [],
    isSubscription: false,
    name: "classic-rower",
    options: [],
    price: 123,
    priceClarification: "a price clarification",
    relatedProducts: [],
    hasSubscriptionPackage: true,
    sku: "someSku",
    slug: "a slug",
    stock: 321,
    stockTracking: false,
    subscriptions: [],
    subtitle: "a subtitle",
    upSellProducts: [],
    variants: [],
  },
  aComModule: {
    bundleItems: [],
    canBuyWithoutStock: false,
    categories: ["Rower"],
    crossSellProducts: [],
    description: "a description",
    id: "someId",
    images: [],
    isSubscription: false,
    name: "comModule",
    options: [],
    price: 123,
    priceClarification: "a price clarification",
    relatedProducts: [],
    hasSubscriptionPackage: true,
    sku: "someSku",
    slug: "a slug",
    stock: 321,
    stockTracking: false,
    subscriptions: [],
    subtitle: "a subtitle",
    upSellProducts: [],
    variants: [],
  },
};
