import { klarnaSessionFixtures } from "../../payment/testing/KlarnaSessionFixtures";
import { cardFixtures } from "./CardFixtures";

export const checkoutFormFixtures = {
  aCheckoutFormPayingWithCard: {
    address: "Olive Drive",
    apartment: "560",
    accountEmail: "test@test.com",
    card: cardFixtures.aCard,
    city: "Ellinwood",
    contactMe: true,
    country: "US",
    firstName: "Test",
    lastName: "User",
    password: "thepassword",
    paymentMethod: "card",
    phone: "620-564-3737",
    postalCode: "67526",
    state: "KS",
    userEmail: "userEmail@test.com",
  },
  aCheckoutFormPayingWithCardWithUserLoggedIn: {
    address: "Olive Drive",
    apartment: "560",
    card: cardFixtures.aCard,
    city: "Ellinwood",
    country: "US",
    firstName: "Test",
    lastName: "User",
    paymentMethod: "card",
    phone: "620-564-3737",
    postalCode: "67526",
    state: "KS",
    userEmail: "userEmail@test.com",
  },
  aCheckoutFormPayingWithKlarna: {
    address: "Olive Drive",
    apartment: "560",
    authorizationToken: "anAuthorizationToken",
    accountEmail: "test@test.com",
    city: "Ellinwood",
    contactMe: true,
    country: "US",
    firstName: "Test",
    klarnaSession: klarnaSessionFixtures.aKlarnaSession,
    lastName: "User",
    password: "thepassword",
    paymentMethod: "klarna",
    phone: "620-564-3737",
    postalCode: "67526",
    state: "KS",
    userEmail: "userEmail@test.com",
  },
};
