import { ecommerceCartItemFixtures } from "./EcommerceCartItemFixtures";

export const ecommerceCartFixtures = {
  anEcommerceCart: {
    couponCode: undefined,
    discounts: 0,
    subscriptionDiscounts: 0,
    discountsList: [],
    id: "someId",
    items: [],
    shippingMethod: "Standard Delivery",
    shippingPrice: 0,
    subTotal: 0,
    tax: 0,
    totalPrice: 0,
    displayTotal: 0,
    discountsByProductMap: {},
    promotionsMap: {},
  },
  anEcommerceCartWithACouponCode: {
    couponCode: "MILITARY10",
    discounts: 0,
    subscriptionDiscounts: 0,
    discountsList: [],
    id: "someId",
    items: [],
    shippingMethod: "Standard Delivery",
    shippingPrice: 0,
    subTotal: 0,
    tax: 0,
    totalPrice: 0,
    displayTotal: 0,
    discountsByProductMap: {},
    promotionsMap: {},
  },
  anEcommerceCartWithMonthlySubscription: {
    couponCode: undefined,
    discounts: 0,
    subscriptionDiscounts: 0,
    discountsList: [],
    id: "someId",
    items: [ecommerceCartItemFixtures.aMonthlySubscriptionItem],
    shippingMethod: "Standard Delivery",
    shippingPrice: 0,
    subTotal: 0,
    tax: 0,
    totalPrice: 0,
    displayTotal: 0,
    discountsByProductMap: {},
    promotionsMap: {},
  },
  anEcommerceCartWithMonthlySubscriptionAndARower: {
    couponCode: undefined,
    discounts: 0,
    subscriptionDiscounts: 0,
    discountsList: [],
    id: "someId",
    items: [ecommerceCartItemFixtures.aMonthlySubscriptionItem, ecommerceCartItemFixtures.aMaxRowerItem],
    shippingMethod: "Standard Delivery",
    shippingPrice: 0,
    subTotal: 0,
    tax: 0,
    totalPrice: 0,
    displayTotal: 0,
    discountsByProductMap: {},
    promotionsMap: {},
  },
  anEcommerceCartWithYearlySubscription: {
    couponCode: undefined,
    discounts: 0,
    subscriptionDiscounts: 0,
    discountsList: [],
    id: "someId",
    items: [ecommerceCartItemFixtures.aYearlySubscriptionItem],
    shippingMethod: "Standard Delivery",
    shippingPrice: 0,
    subTotal: 0,
    tax: 0,
    totalPrice: 0,
    displayTotal: 0,
    discountsByProductMap: {},
    promotionsMap: {},
  },
  anEcommerceCartWithAChargeableYearlySubscription: {
    couponCode: undefined,
    discounts: 0,
    subscriptionDiscounts: 0,
    discountsList: [],
    id: "someId",
    items: [ecommerceCartItemFixtures.aChargeableYearlySubscriptionItem],
    shippingMethod: "Standard Delivery",
    shippingPrice: 0,
    subTotal: 0,
    tax: 0,
    totalPrice: 0,
    displayTotal: 0,
    hasSubscription: true,
    hasSubscriptionPackage: false,
    discountsByProductMap: {},
    promotionsMap: {},
  },
  anEcommerceCartWithAMaxRower: {
    couponCode: undefined,
    coupon: undefined,
    discounts: 0,
    subscriptionDiscounts: 0,
    discountsList: [],
    id: "someId",
    items: [ecommerceCartItemFixtures.aMaxRowerItem],
    shippingMethod: "Standard Delivery",
    shippingPrice: 0,
    subscriptionCoupon: undefined,
    subTotal: 0,
    tax: 0,
    totalPrice: 0,
    displayTotal: 0,
  },
  anEcommerceCartWithAMaxRowerBundle: {
    couponCode: undefined,
    discounts: 0,
    subscriptionDiscounts: 0,
    discountsList: [],
    id: "someId",
    items: [ecommerceCartItemFixtures.aMonthlySubscriptionItem, ecommerceCartItemFixtures.aMaxRowerItem],
    shippingMethod: "Standard Delivery",
    shippingPrice: 0,
    subTotal: 0,
    tax: 0,
    totalPrice: 0,
    displayTotal: 0,
    discountsByProductMap: {},
    promotionsMap: {},
  },
  anEcommerceCartWithAClassicRowerBundle: {
    couponCode: undefined,
    discounts: 0,
    subscriptionDiscounts: 0,
    discountsList: [],
    id: "someId",
    items: [ecommerceCartItemFixtures.aMonthlySubscriptionItem, ecommerceCartItemFixtures.aClassicRowerItem],
    shippingMethod: "Standard Delivery",
    shippingPrice: 0,
    subTotal: 0,
    tax: 0,
    totalPrice: 0,
    displayTotal: 0,
    discountsByProductMap: {},
    promotionsMap: {},
  },
  anEcommerceCartWithAComMod: {
    couponCode: undefined,
    discounts: 0,
    subscriptionDiscounts: 0,
    discountsList: [],
    id: "someId",
    items: [ecommerceCartItemFixtures.aMonthlySubscriptionItem, ecommerceCartItemFixtures.aComModuleItem],
    shippingMethod: "Standard Delivery",
    shippingPrice: 0,
    subTotal: 0,
    tax: 0,
    totalPrice: 0,
    displayTotal: 0,
    discountsByProductMap: {},
    promotionsMap: {},
  },
  anEcommerceWithATShirt: {
    couponCode: undefined,
    discounts: 0,
    subscriptionDiscounts: 0,
    discountsList: [],
    id: "someId",
    items: [ecommerceCartItemFixtures.aTShirtItem],
    shippingMethod: "Standard Delivery",
    shippingPrice: 0,
    subTotal: 0,
    tax: 0,
    totalPrice: 0,
    displayTotal: 0,
    discountsByProductMap: {},
    promotionsMap: {},
  },
};
